server:
  port: 8083
spring:
  datasource:
    url: 'jdbc:postgresql://postgresql_song_service:5432/song_service_db'
    driver-class-name: 'org.postgresql.Driver'
    username: 'postgres'
    password: 'root'
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update